"""init

Revision ID: 7f0db9784f9d
Revises: 
Create Date: 2022-07-03 14:40:13.933459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0db9784f9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=42), nullable=True))
    op.add_column('user', sa.Column('token_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('forgotten_password_token', sa.String(length=42), nullable=True))
    op.add_column('user', sa.Column('forgotten_password_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'forgotten_password_date')
    op.drop_column('user', 'forgotten_password_token')
    op.drop_column('user', 'token_date')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
